pipeline:
  name: Common Deployment Pattern2
  identifier: Common_Deployment_Pattern2
  projectIdentifier: Lloyds_Cloud_Services
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: K8s Deploy2
        identifier: K8s_Deploy2
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Nginx
          environment:
            environmentRef: Test
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Test
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  connectorRef: account.andydpage
  storeType: REMOTE
  filePath: .harness/Common_Deployment_Pattern.yaml
